name: Docker Image CI

on:
  push:
    paths:
      - 'code/*'
      - 'Dockerfile'


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cat ./code/sitename.txt >> $GITHUB_ENV
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        echo "${{ env.sitename }}"
        docker build . --tag sanoopsadique/websitelogger: "${{ env.sitename }}"
        docker push docker.io/sanoopsadique/websitelogger: "${{ env.sitename }}"
